### PR TITLE
Materialize the program. Add and remove some features.

### PR DESCRIPTION
**Pull request by minhducsun2002**
Remove network interfaces and CPU cores frequency.

### CODE REVIEW

**Comment by cszach** [comment]
```javascript
if (arg == "x64") return "AMD64/Intel 64";
if (arg == "ia32") return "IA-32";
if (arg == "x32") return "AMD64/Intel 64 with 32-bit pointers & values"
if (arg == "s390") return "IBM System/390";
if (arg == "arm") return "ARM version 7"
if (arg == "arm64") return "ARM 64-bit";
if (arg == "mips") return "MIPS";
if (arg == "mipsel") return "MIPS little-endian";
```

Why don't ya use `switch`?

**Comment by minhducsun2002** [comment]
@NOVAglow I just forgot that :(

**Comment by dungwinux** [comment]
There's an issue here.
Try highlighting some text then drag it around, the program will be not responding

**Comment by dungwinux** [comment]
Please put cards in one line, else there would be word wrapping

**Comment by minhducsun2002** [comment]
Wasn't I putting cards in one line?

**Comment by minhducsun2002** [comment]
Well check that with the old version if the error persists.

**Comment by minhducsun2002** [comment]
> Try highlighting some text then drag it around, the program will be not responding

Cannot be reproduced on my machine.
You use Windows ?

**Comment by cszach** [comment]
> Try highlighting some text then drag it around, the program will be **not responding**

No need to ask, this is definitely Windows/Advertising.

**Comment by dungwinux** [comment]
I was using GNU/Linux

**Comment by minhducsun2002** [comment]
I cannot reproduce the error.

**Comment by dungwinux** [comment]
Pulled the latest commit, problem's still there

**Comment by dungwinux** [comment]
I'ma skip the dragging crash problem, since it's likely to be ~KDE~ platform problem

**Comment by cszach** [comment]
NUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.

You shouldn't be skipping it.

**Comment by dungwinux** [comment]
Okay, I'm trying to find out what's the actual problem...

**Comment by dungwinux** [comment]
Someone made an issue in Electron
https://github.com/electron/electron/issues/14430

**Comment by dungwinux** [comment]
The _freeze_ problem will be skipped, a patch may be made if the fix affect the code.

**Review by dungwinux — APPROVED** [review]
Good to pull

**Pull request merged**
